import streamlit as st
import sqlite3
import json
import os

st.set_page_config(page_title="School Home Portal - Ultimate Secure Edition", layout="wide")

DB_PATH = "database.db"

def init_db():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # Students Table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS students (
            roll TEXT PRIMARY KEY,
            name TEXT,
            fname TEXT,
            mname TEXT,
            dob TEXT,
            mobile TEXT,
            pan TEXT,
            apar TEXT,
            class_name TEXT,
            exam_type TEXT,
            slno TEXT,
            school TEXT,
            photo TEXT,
            total REAL,
            max_marks REAL,
            grade TEXT,
            status TEXT,
            subjects TEXT
        )
    ''')
    
    # Schools Table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS schools (
            id TEXT PRIMARY KEY,
            name TEXT,
            hm TEXT,
            mobile TEXT,
            state TEXT,
            email TEXT,
            pass TEXT,
            utr TEXT,
            status TEXT,
            upi TEXT,
            baseFee REAL,
            hasGst INTEGER,
            gstPct REAL
        )
    ''')
    
    # Default Schools
    cursor.execute("SELECT COUNT(*) FROM schools")
    if cursor.fetchone()[0] == 0:
        cursor.execute("INSERT INTO schools VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                       ("155CB", "SRI BAIRAGI SARASWATI SISHU VIDYAMANDIR", "ANTARYAMI DAS", "9876543210", "Odisha", "school@gmail.com", "school123", "MANUAL", "Approved", "school155@upi", 500, 1, 18))
        cursor.execute("INSERT INTO schools VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                       ("257CB", "LAXMI NARAYAN GIRLS HIGH SCHOOL", "HEADMASTER", "9876543211", "Odisha", "school2@gmail.com", "school456", "MANUAL2", "Approved", "school257@upi", 500, 1, 18))

    # Insert 42 Students Data with exact PEN & APAAR IDs
    cursor.execute("SELECT COUNT(*) FROM students")
    if cursor.fetchone()[0] == 0:
        students_data = [
            {"roll": "175CB0077", "name": "ADYASHA SAHOO", "mname": "MAMATARANI SAHU", "fname": "UTTAM KUMAR SAHOO", "dob": "20/03/2011", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 87}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 81}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 92}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 69}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 73}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 66}], "total": 468, "max": 600, "grade": "B1", "status": "Pass", "slno": "2611220809", "pan": "21333578409", "apar": "340630618949", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0078", "name": "ALOKTIKA MISHRA", "mname": "SAROJINI MISHRA", "fname": "DEBASIS MISHRA", "dob": "14/02/2011", "gender": "FEMALE", "caste": "GENERAL", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 90}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 67}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 86}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 66}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 70}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 67}], "total": 446, "max": 600, "grade": "B1", "status": "Pass", "slno": "2611220810", "pan": "21182142821", "apar": "704082184322", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0079", "name": "ABHILIPSHA DAS", "mname": "JALPANA DAS", "fname": "HIMANSHU BHUSHAN DAS", "dob": "11/02/2010", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 46}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 34}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 38}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 30}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 39}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 43}], "total": 230, "max": 600, "grade": "E", "status": "Pass", "slno": "2611220811", "pan": "21349438955", "apar": "N/A", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0080", "name": "BAISAKHI SAMAL", "mname": "CHANCHALA SAMAL", "fname": "SUDHAKAR SAMAL", "dob": "26/12/2010", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 87}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 72}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 81}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 57}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 61}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 62}], "total": 420, "max": 600, "grade": "B1", "status": "Pass", "slno": "2611220812", "pan": "21041084790", "apar": "789783065343", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0081", "name": "BARSHA PRIYADARSHANI MOHANTY", "mname": "SUBHADRA MOHANTY", "fname": "PURNA CHANDRA MOHANTY", "dob": "01/10/2010", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 60}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 45}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 58}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 30}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 34}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 41}], "total": 268, "max": 600, "grade": "D", "status": "Pass", "slno": "2611220813", "pan": "21498662821", "apar": "913475687849", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0082", "name": "BARSHARANI KHILAR", "mname": "SANDHYARANI KHILAR", "fname": "SANTOSH KHILAR", "dob": "12/03/2011", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 30}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 33}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 39}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 38}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 30}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 34}], "total": 204, "max": 600, "grade": "E", "status": "Pass", "slno": "2611220814", "pan": "21050451252", "apar": "252741731402", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0083", "name": "BHAGYASHREE MOHANTY", "mname": "RASHMITA MOHANTY", "fname": "ARUN KUMAR MOHANTY", "dob": "11/10/2009", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 41}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 38}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 32}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 38}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 36}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 37}], "total": 222, "max": 600, "grade": "E", "status": "Pass", "slno": "2611220815", "pan": "21082361081", "apar": "642970156338", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0084", "name": "DIPTI MAYEE SETHY", "mname": "BUNI SETHY", "fname": "SANJAY SETHY", "dob": "11/01/2011", "gender": "FEMALE", "caste": "SC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 45}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 32}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 38}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 30}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 30}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 38}], "total": 213, "max": 600, "grade": "E", "status": "Pass", "slno": "2611220816", "pan": "21025149546", "apar": "503511373905", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0085", "name": "HARAPRIYA LENKA", "mname": "SARASWATI LENKA", "fname": "NILAMANI LENKA", "dob": "27/11/2010", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 64}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 51}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 76}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 34}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 50}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 53}], "total": 328, "max": 600, "grade": "C", "status": "Pass", "slno": "2611220817", "pan": "21264457196", "apar": "922843423885", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0086", "name": "JOSODA PARIDA", "mname": "GAURIBALA PARIDA", "fname": "SURENDRA PARIDA", "dob": "01/04/2011", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 73}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 40}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 60}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 31}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 39}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 57}], "total": 300, "max": 600, "grade": "C", "status": "Pass", "slno": "2611220818", "pan": "21697711277", "apar": "618622215960", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0087", "name": "JYOTI SWORUPA PADHI", "mname": "PURNIMA PADHI", "fname": "SUDHANSHU SEKHAR PADHI", "dob": "19/09/2010", "gender": "FEMALE", "caste": "GENERAL", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 62}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 43}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 59}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 39}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 39}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 46}], "total": 288, "max": 600, "grade": "D", "status": "Pass", "slno": "2611220819", "pan": "21067317375", "apar": "135620099184", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0088", "name": "JYOTSHNA RANI BISWAL", "mname": "PRATIMA BISWAL", "fname": "SRABAN KUMAR BISWAL", "dob": "13/10/2010", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 74}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 62}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 77}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 41}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 48}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 64}], "total": 366, "max": 600, "grade": "B2", "status": "Pass", "slno": "2611220820", "pan": "23364745896", "apar": "904172854667", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0089", "name": "LIPA JENA", "mname": "MAMATA JENA", "fname": "MANMATH JENA", "dob": "14/05/2010", "gender": "FEMALE", "caste": "SC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 86}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 72}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 82}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 58}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 64}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 67}], "total": 429, "max": 600, "grade": "B1", "status": "Pass", "slno": "2611220821", "pan": "21109012923", "apar": "593617329877", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0091", "name": "LIZA PADHI", "mname": "RANJITA PADHI", "fname": "RATNAKAR PADHI", "dob": "18/09/2010", "gender": "FEMALE", "caste": "GENERAL", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 70}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 53}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 62}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 42}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 52}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 52}], "total": 331, "max": 600, "grade": "C", "status": "Pass", "slno": "2611220822", "pan": "21064948534", "apar": "777043813613", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0092", "name": "LOVELY PALAI", "mname": "JHUNARANI PALAI", "fname": "PRATAP PALAI", "dob": "25/05/2010", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 48}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 38}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 50}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 32}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 32}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 42}], "total": 242, "max": 600, "grade": "D", "status": "Pass", "slno": "2611220823", "pan": "21311696258", "apar": "671413877266", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0093", "name": "MANISHA SETHY", "mname": "PURNIMA SETHY", "fname": "SUSANTA SETHY", "dob": "12/09/2010", "gender": "FEMALE", "caste": "SC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 37}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 32}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 38}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 34}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 30}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 38}], "total": 209, "max": 600, "grade": "E", "status": "Pass", "slno": "2611220824", "pan": "21106762170", "apar": "611657596631", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0094", "name": "MANISHA JENA", "mname": "SUBHASMITA JENA", "fname": "DILLIP JENA", "dob": "01/05/2010", "gender": "FEMALE", "caste": "SC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 74}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 55}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 65}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 43}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 51}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 54}], "total": 342, "max": 600, "grade": "C", "status": "Pass", "slno": "2611220825", "pan": "21025888551", "apar": "270710056668", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0095", "name": "MITASHREE JENA", "mname": "ANAPURNA JENA", "fname": "KHAGESWAR JENA", "dob": "06/04/2011", "gender": "FEMALE", "caste": "SC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 52}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 40}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 58}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 33}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 40}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 43}], "total": 266, "max": 600, "grade": "D", "status": "Pass", "slno": "2611220826", "pan": "21050476279", "apar": "790335617395", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0096", "name": "PRIYANKA PRIYADARSHINI SAMAL", "mname": "SNEHANJALI SAMAL", "fname": "MANGARAJ SAMAL", "dob": "25/04/2010", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 48}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 40}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 44}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 32}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 41}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 35}], "total": 240, "max": 600, "grade": "D", "status": "Pass", "slno": "2611220827", "pan": "21347860819", "apar": "284100557411", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0097", "name": "PUJARANI MOHANTY", "mname": "DEBAKI MOHANTY", "fname": "AMAR KUMAR MOHANTY", "dob": "08/06/2011", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 66}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 56}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 86}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 30}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 42}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 49}], "total": 329, "max": 600, "grade": "C", "status": "Pass", "slno": "2611220828", "pan": "21086864465", "apar": "408019175598", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0098", "name": "PUJARANI PRUSTY", "mname": "SASMITA PRUSTY", "fname": "RABINDRA PRUSTY", "dob": "22/03/2011", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 67}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 58}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 72}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 35}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 43}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 56}], "total": 331, "max": 600, "grade": "C", "status": "Pass", "slno": "2611220829", "pan": "21264956198", "apar": "360893477685", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0099", "name": "PURBASHA PARIDA", "mname": "JHARANA PARIDA", "fname": "HARINARAYAN PARIDA", "dob": "11/02/2010", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 70}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 41}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 59}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 38}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 38}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 54}], "total": 300, "max": 600, "grade": "C", "status": "Pass", "slno": "2611220830", "pan": "21229203899", "apar": "734196300420", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0100", "name": "RANI JENA", "mname": "KUMUDINI JENA", "fname": "RABINDRA JENA", "dob": "18/11/2010", "gender": "FEMALE", "caste": "SC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 48}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 46}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 48}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 33}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 33}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 37}], "total": 245, "max": 600, "grade": "D", "status": "Pass", "slno": "2611220831", "pan": "21421573731", "apar": "701239984481", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0101", "name": "RADHA RANI BEHERA", "mname": "TAPASWINI BEHERA", "fname": "DEBENDRA NATH BEHERA", "dob": "08/03/2011", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 75}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 68}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 77}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 40}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 43}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 57}], "total": 360, "max": 600, "grade": "B2", "status": "Pass", "slno": "2611220832", "pan": "21402389757", "apar": "724381829344", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0102", "name": "RASHMIREKHA DAS", "mname": "SASMITA DAS", "fname": "NRUSINGHA DAS", "dob": "05/12/2010", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 76}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 62}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 80}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 37}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 50}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 62}], "total": 367, "max": 600, "grade": "B2", "status": "Pass", "slno": "2611220833", "pan": "21050388749", "apar": "919157141678", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0103", "name": "RINU MOHANTY", "mname": "MANORAMA MOHANTY", "fname": "SIBA MOHANTY", "dob": "15/08/2010", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 70}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 55}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 74}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 38}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 43}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 53}], "total": 333, "max": 600, "grade": "C", "status": "Pass", "slno": "2611220834", "pan": "21558866778", "apar": "161232284559", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0104", "name": "ROJALIN PANDA", "mname": "RANJITA PANDA", "fname": "PRATAP KUMAR PANDA", "dob": "17/07/2010", "gender": "FEMALE", "caste": "GENERAL", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 84}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 69}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 82}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 48}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 63}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 57}], "total": 403, "max": 600, "grade": "B2", "status": "Pass", "slno": "2611220835", "pan": "21197126707", "apar": "486947073442", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0105", "name": "SAROJNI BEHERA", "mname": "MEERARANI BEHERA", "fname": "MADAN BEHERA", "dob": "25/12/2010", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 51}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 35}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 48}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 38}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 34}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 34}], "total": 240, "max": 600, "grade": "D", "status": "Pass", "slno": "2611220836", "pan": "21024509156", "apar": "377751563500", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0106", "name": "SHRABANI SAHOO", "mname": "DIPALI SAHOO", "fname": "BIDYADHAR SAHOO", "dob": "29/07/2010", "gender": "FEMALE", "caste": "GENERAL", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 81}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 73}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 84}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 77}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 54}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 58}], "total": 427, "max": 600, "grade": "B1", "status": "Pass", "slno": "2611220837", "pan": "21031034330", "apar": "536352323335", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0107", "name": "SHRIYA PARIDA", "mname": "JYOTSNARANI PARIDA", "fname": "ASHOK KUMAR PARIDA", "dob": "04/06/2010", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 64}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 38}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 62}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 31}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 31}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 46}], "total": 272, "max": 600, "grade": "D", "status": "Pass", "slno": "2611220838", "pan": "21704868439", "apar": "833200620741", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0108", "name": "SMRUTIREKHA KHILLAR", "mname": "SABITA KHILLAR", "fname": "CHHABINDRA KHILLAR", "dob": "08/03/2011", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 42}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 44}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 40}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 38}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 37}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 39}], "total": 240, "max": 600, "grade": "D", "status": "Pass", "slno": "2611220839", "pan": "21515201906", "apar": "856403020289", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0109", "name": "SMRUTIREKHA SAHOO", "mname": "PRAMILA SAHOO", "fname": "BIJAY KUMAR SAHOO", "dob": "09/11/2009", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 82}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 69}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 75}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 54}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 56}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 62}], "total": 398, "max": 600, "grade": "B2", "status": "Pass", "slno": "2611220840", "pan": "21158801854", "apar": "845483054020", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0110", "name": "SRUTINGYA KHILAR", "mname": "SABITRI KHILAR", "fname": "BISWANATH KHILAR", "dob": "09/12/2010", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 82}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 71}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 94}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 66}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 65}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 80}], "total": 458, "max": 600, "grade": "B1", "status": "Pass", "slno": "2611220841", "pan": "21013751501", "apar": "240564234821", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0111", "name": "SUBHADRA BEHERA", "mname": "REENARANI BEHERA", "fname": "AJAYA BEHERA", "dob": "13/03/2011", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 67}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 66}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 74}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 44}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 52}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 65}], "total": 368, "max": 600, "grade": "B2", "status": "Pass", "slno": "2611220842", "pan": "21697498328", "apar": "346161684808", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0112", "name": "SUBHASMITA PANDA", "mname": "HEMALATA PANDA", "fname": "NARAYAN PANDA", "dob": "07/09/2010", "gender": "FEMALE", "caste": "GENERAL", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 66}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 52}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 56}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 31}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 44}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 51}], "total": 300, "max": 600, "grade": "C", "status": "Pass", "slno": "2611220843", "pan": "21013361804", "apar": "549518813294", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0113", "name": "SHUBHASMITA SAMANTA", "mname": "SASMITA SAMANTA", "fname": "BHASKAR CHANDRA SAMANTA", "dob": "26/02/2010", "gender": "FEMALE", "caste": "GENERAL", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 57}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 42}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 56}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 31}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 38}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 50}], "total": 274, "max": 600, "grade": "D", "status": "Pass", "slno": "2611220844", "pan": "21077897450", "apar": "939307473716", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0114", "name": "SWAPNARANI PARIDA", "mname": "RADHARANI PARIDA", "fname": "HAREKRUSHNA PARIDA", "dob": "21/12/2010", "gender": "FEMALE", "caste": "GENERAL", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 61}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 50}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 69}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 34}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 46}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 62}], "total": 322, "max": 600, "grade": "C", "status": "Pass", "slno": "2611220845", "pan": "21060625257", "apar": "807530411559", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0115", "name": "SWOPNA JENA", "mname": "BASANTI JENA", "fname": "MUKTIKANTA JENA", "dob": "09/08/2010", "gender": "FEMALE", "caste": "SC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 35}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 32}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 31}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 32}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 34}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 34}], "total": 198, "max": 600, "grade": "E", "status": "Pass", "slno": "2611220846", "pan": "21073087895", "apar": "795235253070", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0116", "name": "TRUPTI REKHA BARIK", "mname": "RANJULATA BARIK", "fname": "RABINDRA BARIK", "dob": "01/02/2010", "gender": "FEMALE", "caste": "SEBC", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 62}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 45}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 57}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 38}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 40}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 42}], "total": 284, "max": 600, "grade": "D", "status": "Pass", "slno": "2611220847", "pan": "21358384708", "apar": "393771061550", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0117", "name": "UME SALMA", "mname": "FAIZUN NESHA", "fname": "SHAH MD QUAMRUDDIN", "dob": "19/04/2010", "gender": "FEMALE", "caste": "GENERAL", "category": "SR", "subjects": [{"code": "FLU", "name": "FIRST LANGUAGE URDU", "max": 100, "sec": 60}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 55}, {"code": "TLH", "name": "THIRD LANGUAGE HINDI", "max": 100, "sec": 48}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 33}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 42}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 48}], "total": 286, "max": 600, "grade": "D", "status": "Pass", "slno": "2611220848", "pan": "21354154825", "apar": "156117659572", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""},
            {"roll": "175CB0118", "name": "YANJYASENI DAS", "mname": "KABITA BEHURIA", "fname": "SUSANTA DAS", "dob": "01/11/2010", "gender": "FEMALE", "caste": "GENERAL", "category": "SR", "subjects": [{"code": "FLO", "name": "FIRST LANGUAGE ODIA", "max": 100, "sec": 38}, {"code": "SLE", "name": "SECOND LANGUAGE ENGLISH", "max": 100, "sec": 30}, {"code": "TLS", "name": "THIRD LANGUAGE SANSKRIT", "max": 100, "sec": 38}, {"code": "MTH", "name": "MATHEMATICS", "max": 100, "sec": 32}, {"code": "GSC", "name": "GENERAL SCIENCE", "max": 100, "sec": 35}, {"code": "SSC", "name": "SOCIAL SCIENCE", "max": 100, "sec": 34}], "total": 207, "max": 600, "grade": "E", "status": "Pass", "slno": "2611220849", "pan": "21072379693", "apar": "147250355555", "school": "LAXMI NARAYAN GIRLS HIGH SCHOOL", "class_name": "X", "exam_type": "ANNUAL", "photo": ""}
        ]
        
        for s in students_data:
            cursor.execute("INSERT OR REPLACE INTO students VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                           (s['roll'], s['name'], s['fname'], s['mname'], s['dob'], s.get('mobile', ''), s['pan'], s['apar'], 
                            s['class_name'], s['exam_type'], s['slno'], s['school'], s.get('photo', ''), s['total'], s['max'], s['grade'], s['status'], json.dumps(s['subjects'])))

    conn.commit()
    conn.close()

init_db()

# Render HTML template with DB students data
with open("index.html", "r", encoding="utf-8") as f:
    html_content = f.read()

st.components.v1.html(html_content, height=900, scrolling=True)
